version: "3.8"

services:
  php:
    build:
      context: .
    ports:
      - "8000:80"
      - "9003:9003" 
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: client_host=172.30.0.1 client_port=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always





