services:
  xss-demo:
    build: .
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www/html


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    ports:
      - "3306:3306"
    # restart: always
