services:
  src:
    build: .
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:8.0
    container_name: mysql-mysql_container

    command: >
          bash -c "
          chmod 0444 /etc/my.cnf
          && /entrypoint.sh mysqld
          "
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/my.cnf:/etc/my.cnf
    ports:
      - "3306:3306"
    restart: always