services:
  src:
    build: 
      context: .
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html #for debugging

  db:
    image: mysql:8.0
    container_name: mysql-container

    command: >
          bash -c "
          chmod 0444 /etc/my.cnf
          && /entrypoint.sh mysqld
          "
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: demo
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config/my.cnf:/etc/my.cnf
    ports:
      - "3307:3307"
    restart: always